# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='название')),
                ('album_slug', models.SlugField(max_length=150, verbose_name='Транслит')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='albome/photos', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albome/photos', verbose_name='изображение')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albome.Album', verbose_name='альбом')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-album__date'],
            },
        ),
    ]
