# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(verbose_name='Дата проекта'),
        ),
    ]
