# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0002_auto_20170613_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_slug',
            field=models.SlugField(max_length=150),
        ),
    ]
